# Site settings
environment: production
destination: ./_site/
title: SparkPost Developer Hub
email: developers@sparkpost.com
description: >
  SparkPost provides email delivery and analytics built for
  developers. Our developer hub is a collection of resources to help you succeed
  with SparkPost. What will you build?
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://developers.sparkpost.com" # the base hostname & protocol for your site
twitter_username: SparkPost
github_username:  SparkPost
facebook_username: SparkPost
facebook_app_id: 1078423545531734
relay_webhook_consumer_url_base: "https://relay-webhook-consumer.herokuapp.com"

collections:
  contributors:
    output: true
  hackathons:
    output: true
  api:
    output: true

defaults:
  - scope:
      path: ""
      type: contributors
    values:
      layout: contributor
  - scope:
      path: ""
      type: hackathons
    values:
      layout: hackathon

# Build settings
markdown: kramdown

# Deploy settings
username: sparkpost
repo: developers.sparkpost.com
branch: develop

gems:
  - jemoji

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - Guardfile
  - bower.json
  - /bin
  - /script
