[build]
  publish = "./public"
  command = "npm run bootstrap && netlify-lambda build lambda/ && npm run build"
  functions = "./functions"

# Run `npm run publish` to re-index in algolia
[context.production]
  command = "npm run bootstrap && netlify-lambda build lambda/ && npm run publish"
